### ISSUE TITLE
Add macOS and WASM support

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Ch9#45]
## What would you like to be added:

Support for macOS and WASM to show Uno Platform in full.

## Why is this needed:

🎉

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks

**Comment by jeremiethibeault** [comment]
Closed by #85
